./FunctionalDS rbtree insert front; 
./FunctionalDS rbtree insert back; 
./FunctionalDS rbtree insert random; 
./FunctionalDS rbtree delete front; 
./FunctionalDS rbtree delete back; 
./FunctionalDS rbtree delete random;
./FunctionalDS bitvectri insert back; 
./FunctionalDS bitvectri delete  back;
./FunctionalDS bankersqueue insert; 
./FunctionalDS bankersqueue delete;
 ./FunctionalDS list insert; 
 ./FunctionalDS list delete;
 ./FunctionalDS nfstack insert; 
 ./FunctionalDS nfstack delete; 
 ./FunctionalDS nfqueue insert; 
 ./FunctionalDS nfqueue delete;
 ./FunctionalDS nfmap insert front;
 ./FunctionalDS nfmap insert back; 
 ./FunctionalDS nfmap insert random; 
 ./FunctionalDS nfmap delete front; 
 ./FunctionalDS nfmap delete back; 
 ./FunctionalDS nfmap delete random; 
 ./FunctionalDS nfvector insert; 
 ./FunctionalDS nfvector delete;
